// Solid/App.jsx
import { createSignal, createEffect } from 'solid-js';
import { createStore } from 'solid-js/store';
import './style.css';

function App() {
  const [products, setProducts] = createStore([]);
  const [showModal, setShowModal] = createSignal(false);
  const [selectedProduct, setSelectedProduct] = createStore({});

  createEffect(async () => {
    try {
      const response = await fetch('https://dummyjson.com/products');
      const data = await response.json();
      setProducts(data.products);
    } catch (error) {
      console.error(error);
    }
  });

  const handleEditProduct = (product) => {
    setSelectedProduct(product);
    setShowModal(true);
  };

  const handleSaveProduct = () => {
    const updatedProduct = {
      ...selectedProduct,
      title: document.getElementById('title').value,
      description: document.getElementById('description').value,
      price: Number(document.getElementById('price').value),
    };
    const updatedProducts = [...products];
    const index = updatedProducts.findIndex(
      (product) => product.id === updatedProduct.id
    );
    updatedProducts[index] = updatedProduct;
    setProducts(updatedProducts);
    setShowModal(false);
  };

  const handleCancelEdit = () => {
    setShowModal(false);
  };

  const renderModal = () => {
    return (
      showModal() && (
        <div class="modal">
          <div class="modal-content">
            <h2>Edit Product</h2>
            <form>
              <label for="title">Title:</label>
              <input type="text" id="title" value={selectedProduct.title} />
              <label for="description">Description:</label>
              <textarea
                id="description"
                value={selectedProduct.description}
              ></textarea>
              <label for="price">Price:</label>
              <input type="number" id="price" value={selectedProduct.price} />
              <div class="modal-buttons">
                <button type="button" onClick={handleSaveProduct}>
                  Save
                </button>
                <button type="button" onClick={handleCancelEdit}>
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      )
    );
  };

  const renderTable = () => {
    return (
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Description</th>
            <th>Price</th>
            <th>Thumbnail</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {products.map((product) => (
            <tr>
              <td>{product.id}</td>
              <td>{product.title}</td>
              <td>{product.description}</td>
              <td>${product.price.toFixed(2)}</td>
              <td>
                <img
                  src={product.thumbnail}
                  alt={product.title}
                  style="max-width: 100px"
                />
              </td>
              <td>
                <button onClick={() => handleEditProduct(product)}>Edit</button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    );
  };

  return (
    <div>
      {renderTable()}
      {renderModal()}
    </div>
  );
}

export default App;

// Angular/app.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

interface Product {
  id: number;
  title: string;
  description: string;
  price: number;
  thumbnail: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  products: Product[] = [];
  editedProduct: Product | null = null;
  modalActive = false;

  constructor(private http: HttpClient) { }

  ngOnInit(): void {
    this.fetchProducts();
  }

  fetchProducts(): void {
    this.http.get<{ products: Product[] }>('https://dummyjson.com/products')
      .subscribe(response => {
        this.products = response.products;
      }, error => {
        console.log('Failed to fetch products', error);
      });
  }

  editProduct(product: Product): void {
    this.editedProduct = { ...product };
    this.modalActive = true;
  }

  saveProduct(): void {
    if (this.editedProduct) {
      const index = this.products.findIndex(p => p.id === this.editedProduct!.id);
      if (index >= 0) {
        this.products[index] = { ...this.editedProduct };
      }
      this.editedProduct = null;
      this.modalActive = false;
    }
  }

  cancelEdit(): void {
    this.editedProduct = null;
    this.modalActive = false;
  }
}
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Thumbnail</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let product of products">
      <td>{{product.id}}</td>
      <td>{{product.title}}</td>
      <td>{{product.description}}</td>
      <td>{{product.price}}</td>
      <td><img [src]="product.thumbnail" [style.width.px]="100"></td>
      <td><button (click)="editProduct(product)">Edit</button></td>
    </tr>
  </tbody>
</table>

<div class="modal" [class.active]="modalActive">
  <div class="modal-content" *ngIf="editedProduct">
    <h2>Edit Product</h2>
    <form>
      <label>
        Title:
        <input type="text" [(ngModel)]="editedProduct.title" name="title">
      </label>
      <label>
        Description:
        <textarea [(ngModel)]="editedProduct.description" name="description"></textarea>
      </label>
      <label>
        Price:
        <input type="number" [(ngModel)]="editedProduct.price" name="price">
      </label>
      <button type="button" (click)="saveProduct()">Save</button>
      <button type="button" (click)="cancelEdit()">Cancel</button>
    </form>
  </div>
</div>
